#!/usr/bin/env ruby

require 'fileutils'
require 'benchmark'

TASK = ARGV[0]

if(TASK.nil?)
  puts("USAGE: ./run ant_colony")
  abort
end

FileUtils.mkdir_p('tmp')

source = File.join('src', TASK, 'main.cpp')
binary = File.join('tmp', TASK)

if(system("g++ -O2 -o #{binary} #{source}"))
  Dir['data/*.in'].sort.each do |input|
    output = ""
    result = Benchmark.measure { output = `#{binary} < #{input}` }
    $stderr.puts("#{input}: #{result}")
    puts(output)
  end
end

FileUtils.rmtree('tmp')
